"use strict";

const fields = ["species", "genus", "family", "deciduous", "species_dutch", "family_dutch", "native", "tree", "hybrid"];
const fields_dutch = ["soort_latijn", "geslacht_latijn", "familie_latijn", "bladverliezend", "soort", "familie", "inheems", "boom", "hybride"]

const species = [
  ["Acer buergerianum", "Acer", "Sapindaceae", true, "Acer buergerianum", "Zeepboomfamilie", false, true, null],
  ["Acer campestre", "Acer", "Sapindaceae", true, "Spaanse aak of veldesdoorn", "Zeepboomfamilie", true, true, null],
  ["Acer capillipes", "Acer", "Sapindaceae", true, "Slangenesdoorn", "Zeepboomfamilie", false, true, null],
  ["Acer cappadocicum", "Acer", "Sapindaceae", true, "Colchische esdoorn", "Zeepboomfamilie", false, true, null],
  ["Acer cissifolium", "Acer", "Sapindaceae", true, "vine-leafed maple", "Zeepboomfamilie", false, false, null],
  ["Acer davidii", "Acer", "Sapindaceae", true, "Père David's maple", "Zeepboomfamilie", false, true, null],
  ["Acer ginnala", "Acer", "Sapindaceae", true, "Amoeresdoorn", "Zeepboomfamilie", false, true, null],
  ["Acer heldreichii", "Acer", "Sapindaceae", true, "Acer heldreichii", "Zeepboomfamilie", false, true, null],
  ["Acer negundo", "Acer", "Sapindaceae", true, "Vederesdoorn", "Zeepboomfamilie", false, true, null],
  ["Malus florentina", "Malus", "Rosaceae", true, "Florentine crabapple ", "Rozenfamilie", false, true, null],
  ["Malus floribunda", "Malus", "Rosaceae", true, "Japanse wilde appel", "Rozenfamilie", false, true, null],
  ["Malus fusca ", "Malus", "Rosaceae", true, "Oregon/Pacific crabapple", "Rozenfamilie", false, true, null],
  ["Malus glabrata", "Malus", "Rosaceae", true, "Biltmore's crabapple", "Rozenfamilie", false, true, null],
  ["Malus glaucescens", "Malus", "Rosaceae", true, "Dunbar crabapple", "Rozenfamilie", false, true, null],
  ["Malus halliana", "Malus", "Rosaceae", true, "Hall crabapple", "Rozenfamilie", false, true, null],
  ["Malus honanensis", "Malus", "Rosaceae", true, "Malus honanensis", "Rozenfamilie", false, true, null],
  ["Malus hupehensis ", "Malus", "Rosaceae", true, "Chinese crab apple (Tea apple)", "Rozenfamilie", false, true, null],
  ["Malus ioensis", "Malus", "Rosaceae", true, "Prairie crabapple", "Rozenfamilie", false, true, null],
  ["Malus kansuensis", "Malus", "Rosaceae", true, "Calva crabapple", "Rozenfamilie", false, true, null],
  ["Malus niedzwetskyana", "Malus", "Rosaceae", true, "Niedzwetzky's apple", "Rozenfamilie", false, true, null],
  ["Malus prattii", "Malus", "Rosaceae", true, "Pratt's crabapple", "Rozenfamilie", false, true, null],
  ["Malus prunifolia", "Malus", "Rosaceae", true, "plumleaf crab apple", "Rozenfamilie", false, true, null],
  ["Malus pumila", "Malus", "Rosaceae", true, "Appel (eetbare appels)", "Rozenfamilie", false, true, null],
  ["Malus rockii", "Malus", "Rosaceae", true, "Malus rockii", "Rozenfamilie", false, true, null],
  ["Malus sargentii", "Malus", "Rosaceae", true, "Sargent's apple", "Rozenfamilie", false, true, null],
  ["Malus sikkimensis", "Malus", "Rosaceae", true, "Sikkim crabapple", "Rozenfamilie", false, true, null],
  ["Malus spectabilis", "Malus", "Rosaceae", true, "Asiatic apple", "Rozenfamilie", false, true, null],
  ["Malus sublobata", "Malus", "Rosaceae", true, "yellow autumn crabapple", "Rozenfamilie", false, true, null],
  ["Malus sylvestris", "Malus", "Rosaceae", true, "Wilde appel", "Rozenfamilie", true, true, null],
  ["Malus toringo", "Malus", "Rosaceae", true, "Siebold's crab apple", "Rozenfamilie", false, true, null],
  ["Malus tschonoskii", "Malus", "Rosaceae", true, "Chonosuki crab", "Rozenfamilie", false, true, null],
  ["Malus transitoria", "Malus", "Rosaceae", true, "cut-leaf crabapple", "Rozenfamilie", false, true, null],
  ["Malus trilobata", "Malus", "Rosaceae", true, "Lebanese wild apple", "Rozenfamilie", false, true, null],
  ["Malus yunnanensis", "Malus", "Rosaceae", true, "Yunnan crabapple", "Rozenfamilie", false, true, null],
  ["Populus adenopoda", "Populus", "Salicaceae", true, "Chinese aspen", "Wilgenfamilie", false, true, null],
  ["Populus alba", "Populus", "Salicaceae", true, "Witte abeel of Zilverpopulier", "Wilgenfamilie", true, true, null],
  ["Populus angustifolia", "Populus", "Salicaceae", true, "Smalbladige populier", "Wilgenfamilie", false, true, null],
  ["Populus balsamifera", "Populus", "Salicaceae", true, "Balsampopulier", "Wilgenfamilie", false, true, null],
  ["Populus x berolinensis", "Populus", "Salicaceae", true, "Siberische balsempopulier", "Wilgenfamilie", false, true, null],
  ["Populus canescens", "Populus", "Salicaceae", true, "Grauwe abeel", "Wilgenfamilie", true, true, null],
  ["Populus deltoides", "Populus", "Salicaceae", true, "Amerikaanse zwarte populier", "Wilgenfamilie", true, true, null],
  ["Populus fremontii", "Populus", "Salicaceae", true, "Fremont's cottonwood", "Wilgenfamilie", false, true, null],
  ["Populus grandidentata", "Populus", "Salicaceae", true, "Grofgetande populier", "Wilgenfamilie", false, true, null],
  ["Populus heterophylla", "Populus", "Salicaceae", true, "Hartbladige populier", "Wilgenfamilie", false, true, null],
  ["Populus lasiocarpa", "Populus", "Salicaceae", true, "Ruwvruchtige populier", "Wilgenfamilie", false, true, null],
  ["Populus laurifolia", "Populus", "Salicaceae", true, "Laurierpopulier", "Wilgenfamilie", false, true, null],
  ["Populus maximowiczii", "Populus", "Salicaceae", true, "Koreaanse balsempopulier", "Wilgenfamilie", false, true, null],
  ["Populus nigra", "Populus", "Salicaceae", true, "Zwarte populier", "Wilgenfamilie", true, true, null],
  ["Populus sieboldii", "Populus", "Salicaceae", true, "Japanese aspen", "Wilgenfamilie", false, true, null],
  ["Populus simonii", "Populus", "Salicaceae", true, "Chinese balsempopulier", "Wilgenfamilie", false, true, null],
  ["Populus tremula", "Populus", "Salicaceae", true, "Ratelpopulier", "Wilgenfamilie", true, true, null],
  ["Populus tremuloides", "Populus", "Salicaceae", true, "Amerikaanse ratelpopulier", "Wilgenfamilie", false, true, null],
  ["Populus trichocarpa", "Populus", "Salicaceae", true, "Westamerikaanse balsempopulier", "Wilgenfamilie", false, true, null],
  ["Populus wilsonii", "Populus", "Salicaceae", true, "Wilson-populier", "Wilgenfamilie", false, true, null],
  ["Prunus avium", "Prunus", "Rosaceae", true, "Zoete kers", "Rozenfamilie", true, true, null],
  ["Prunus cerasifera", "Prunus", "Rosaceae", true, "Kerspruim", "Rozenfamilie", false, true, null],
  ["Prunus cerasus", "Prunus", "Rosaceae", true, "Zure kers", "Rozenfamilie", false, true, null],
  ["Prunus domestica", "Prunus", "Rosaceae", true, "Pruim", "Rozenfamilie", false, true, null],
  ["Crataegus crus-galli", "Crataegus", "Rosaceae", true, "Crataegus crus-galli", "Rozenfamilie", false, true, null],
  ["Crataegus laevigata", "Crataegus", "Rosaceae", true, "Tweestijlige meidoorn", "Rozenfamilie", true, false, null],
  ["Crataegus monogyna", "Crataegus", "Rosaceae", true, "Eenstijlige meidoorn", "Rozenfamilie", false, true, null],
  ["Crataegus grignonensis", "Crataegus", "Rosaceae", true, "Grignon hawthorn", "Rozenfamilie", false, true, null],
  ["Crataegus lavalleei", "Crataegus", "Rosaceae", true, "Lavallée's hawthorn", "Rozenfamilie", false, true, null],
  ["Crataegus pinnatifida", "Crataegus", "Rosaceae", true, "mountain hawthorn", "Rozenfamilie", false, true, null],
  ["Crataegus persimillis", "Crataegus", "Rosaceae", true, "meidoorn cultivar", "Rozenfamilie", false, true, null],
  ["Cydonia oblonga", "Cydonia", "Rosaceae", true, "Kweepeer", "Rozenfamilie", false, true, null],
  ["Elaeagnus angustifolia", "Elaeagnus", "Elaeagnaceae", true, "Smalbladige olijfwilg", "Duindoornfamilie", false, true, null],
  ["Malus ×micromalus", "Malus", "Rosaceae", true, "Midget crabapple", "Rozenfamilie", false, true, true],
  ["Malus ×zumi", "Malus", "Rosaceae", true, "Malus professor Sprenger", "Rozenfamilie", false, true, true],
  ["Populus ×canadensis", "Populus", "Salicaceae", true, "Canadese populier", "Wilgenfamilie", false, true, true],
  ["Prunus ×eminens", "Prunus", "Rosaceae", true, "Prunus 'Umbraculifera'", "Rozenfamilie", false, true, true],
  ["Mespilus germanica", "Mespilus", "Rosaceae", true, "Mispel", "Rozenfamilie", true, true, null],
  ["Olea europaea", "Olea", "Oleaceae", true, "Olijfboom", "Olijffamilie", false, true, null],
  ["Fraxinus excelsior", "Fraxinus", "Oleaceae", true, "Es", "Olijffamilie", true, true, null],
  ["Rhamnus cathartica", "Rhamnus", "Rhamnaceae", true, "Wegedoorn", "Wegedoornfamilie", true, true, null],
  ["Rhamnus frangula", "Rhamnus", "Rhamnaceae", true, "Sporkehout", "Wegedoornfamilie", true, true, null],
  ["Salix aegyptiaca", "Salix", "Salicaceae", true, "Salix aegyptiaca", "Wilgenfamilie", true, true, null],
  ["Salix alba", "Salix", "Salicaceae", true, "Schietwilg", "Wilgenfamilie", true, true, null],
  ["Salix americana", "Salix", "Salicaceae", true, "Salix americana", "Wilgenfamilie", true, true, null],
  ["Salix aquatica", "Salix", "Salicaceae", true, "Salix aquatica", "Wilgenfamilie", true, true, null],
  ["Salix aurita", "Salix", "Salicaceae", true, "Geoorde wilg", "Wilgenfamilie", true, true, null],
  ["Salix babylonica", "Salix", "Salicaceae", true, "Treurwilg", "Wilgenfamilie", true, true, null],
  ["Salix caprea", "Salix", "Salicaceae", true, "Boswilg of Waterwilg", "Wilgenfamilie", true, true, null],
  ["Salix cinerea", "Salix", "Salicaceae", true, "Grauwe wilg", "Wilgenfamilie", true, true, null],
  ["Salix daphnoides", "Salix", "Salicaceae", true, "Berijpte wilg", "Wilgenfamilie", false, true, null],
  ["Salix dasyclados", "Salix", "Salicaceae", true, "Duitse dot", "Wilgenfamilie", false, true, null],
  ["Salix elaeagnos", "Salix", "Salicaceae", true, "Grijze wilg", "Wilgenfamilie", false, true, null],
  ["Salix fluviatilis", "Salix", "Salicaceae", true, "Salix fluviatilis", "Wilgenfamilie", true, true, null],
  ["Salix fragilis", "Salix", "Salicaceae", true, "Kraakwilg", "Wilgenfamilie", true, true, null],
  ["Salix matsudana", "Salix", "Salicaceae", true, "Chinese wilg", "Wilgenfamilie", true, true, null],
  ["Salix nigricans", "Salix", "Salicaceae", true, "Zwarte wilg", "Wilgenfamilie", false, true, null],
  ["Salix pentandra", "Salix", "Salicaceae", true, "Laurierwilg", "Wilgenfamilie", true, true, null],
  ["Salix purpurea", "Salix", "Salicaceae", true, "Bittere wilg", "Wilgenfamilie", true, true, null],
  ["Salix repens", "Salix", "Salicaceae", true, "Kruipwilg", "Wilgenfamilie", false, true, null],
  ["Salix salviaefolia", "Salix", "Salicaceae", true, "Salix salviaefolia", "Wilgenfamilie", true, true, null],
  ["Salix schwerinii", "Salix", "Salicaceae", true, "Salix schwerinii", "Wilgenfamilie", true, true, null],
  ["Salix sepulcralis ", "Salix", "Salicaceae", true, "white weeping willow", "Wilgenfamilie", false, true, null],
  ["Pyrus pyraster", "Pyrus", "Rosaceae", true, "Wilde peer", "Rozenfamilie", true, true, null],
  ["Alnus spaethii", "Alnus", "Betulaceae", true, "Japanse Kaukasische els", "Berkenfamilie", false, true, null],
  ["Abies grandis", "Abies", "Pinaceae", false, "Reuzenzilverspar", "Dennenfamilie", true, true, null],
  ["Abies koreana", "Abies", "Pinaceae", false, "Koreaanse zilverspar", "Dennenfamilie", false, true, null],
  ["Abies nordmanniana", "Abies", "Pinaceae", false, "Nordmannspar", "Dennenfamilie", true, true, null],
  ["Ginkgo biloba", "Ginkgo", "Ginkgoaceae", true, "Japanse notenboom of gingko", "", false, true, null],
  ["Abies procera", "Abies", "Pinaceae", false, "Edele zilverspar", "Dennenfamilie", false, true, null],
  ["Abies veitchii", "Abies", "Pinaceae", false, "Veitch zilverspar of Japanse zilverspar", "Dennenfamilie", false, true, null],
  ["Liquidambar styraciflua", "Liquidambar", "Altingiaceae", true, "Amberboom", "", false, true, null],
  ["Araucaria araucana", "Araucaria", "Araucariaceae", false, "Slangenden of apenboom", "Apenboomfamilie", false, true, null],
  ["Arbutus unedo", "Arbutus", "Ericaceae", false, "Aardbeiboom", "Heidefamilie", false, true, null],
  ["Calocedrus decurrens", "Calocedrus", "Cupressaceae", false, "Wierookceder", "Cipresfamilie", false, true, null],
  ["Cedrus atlantica", "Cedrus", "Pinaceae", false, "Atlasceder", "Dennenfamilie", false, true, null],
  ["Cedrus deodara", "Cedrus", "Pinaceae", false, "Himalayaceder", "Dennenfamilie", false, true, null],
  ["Cedrus libani", "Cedrus", "Pinaceae", false, "Libanonceder", "Dennenfamilie", false, true, null],
  ["Cephalotaxus fortunei", "Cephalotaxus", "Cephalotaxaceae", false, "Chinese knoptaxus", "Knoptaxusfamilie", false, true, null],
  ["Cephalotaxus harringtonia", "Cephalotaxus", "Cephalotaxaceae", false, "Japanse knoptaxus", "Knoptaxusfamilie", false, true, null],
  ["Ilex aquifolium", "Ilex", "Aquifoliaceae", false, "Hulst", "Hulstfamilie", true, true, null],
  ["Ilex crenata", "Ilex", "Aquifoliaceae", false, "Japanse hulst", "Hulstfamilie", false, true, null],
  ["Juniperus communis", "Juniperus", "Cupressaceae", false, "Jeneverbes", "Cipresfamilie", true, false, null],
  ["Larix decidua", "Larix", "Pinaceae", false, "Europese larix", "Dennenfamilie", true, true, null],
  ["Ailanthus altissima", "Ailanthus", "Simaroubaceae", true, "Hemelboom", "Hemelboomfamilie", false, true, null],
  ["Albizia julibrissin", "Albizia", "Fabaceae", true, "Perzische slaapboom", "Vlinderbloemenfamilie", false, true, null],
  ["Alnus cordata", "Alnus", "Betulaceae", true, "Hartbladige els", "Berkenfamilie", false, true, null],
  ["Alnus glutinosa", "Alnus", "Betulaceae", true, "Zwarte els", "Berkenfamilie", true, true, null],
  ["Alnus incana", "Alnus", "Betulaceae", true, "Witte els, grauwe els of grijze els", "Berkenfamilie", true, true, null],
  ["Laburnum ×watereri", "Laburnum", "Fabaceae", true, "Laburnum hybride", "Vlinderbloemenfamilie", null, null, true],
  ["Magnolia ×soulangiana", "Magnolia", "Magnoliaceae", true, "Magnolia soulangiana", "Tulpenboomfamilie", false, true, true],
  ["Alnus rubra", "Alnus", "Betulaceae", true, "the red alder", "Berkenfamilie", false, true, null],
  ["Alnus subcordata ", "Alnus", "Betulaceae", true, "Caucasian Alder", "Berkenfamilie", false, true, null],
  ["Alnus viridis", "Alnus", "Betulaceae", true, "Groene els, bergels of alpenels", "Berkenfamilie", false, true, null],
  ["Betula albosinensis", "Betula", "Betulaceae", true, "Chinese berk", "Berkenfamilie", false, true, null],
  ["Betula ermanii", "Betula", "Betulaceae", true, "Goudberk", "Berkenfamilie", false, true, null],
  ["Betula lenta", "Betula", "Betulaceae", true, "Suikerberk", "Berkenfamilie", false, true, null],
  ["Betula maximowicziana", "Betula", "Betulaceae", true, "Grootbladige berk", "Berkenfamilie", false, true, null],
  ["Betula nigra", "Betula", "Betulaceae", true, "Rode berk of zwarte berk", "Berkenfamilie", false, true, null],
  ["Betula papyrifera", "Betula", "Betulaceae", true, "Papierberk", "Berkenfamilie", false, true, null],
  ["Betula pendula", "Betula", "Betulaceae", true, "Ruwe berk", "Berkenfamilie", true, true, null],
  ["Betula pubescens", "Betula", "Betulaceae", true, "Zachte berk", "Berkenfamilie", true, true, null],
  ["Betula utilis", "Betula", "Betulaceae", true, "Witte Himalayaberk of Himalayaberk", "Berkenfamilie", false, true, null],
  ["Carpinus betulus", "Carpinus", "Betulaceae", true, "Haagbeuk", "Berkenfamilie", true, true, null],
  ["Carya ovata", "Carya", "Juglandaceae", true, "Carya ovata", "Okkernootfamilie", false, true, null],
  ["Castanea sativa", "Castanea", "Fagaceae", true, "Tamme kastanje", "Napjesdragersfamilie", true, true, null],
  ["Parrotia persica", "Parrotia", "Hamamelidaceae", true, "Perzisch ijzerhout", "", false, true, null],
  ["Paulownia tomentosa", "Paulownia", "Paulowniaceae", true, "Anna Paulownaboom", "", false, true, null],
  ["Catalpa bignonioides", "Catalpa", "Bignoniaceae", true, "Groene trompetboom", "Trompetboomfamilie", false, true, null],
  ["Catalpa speciosa", "Catalpa", "Bignoniaceae", true, "northern catalpa", "Trompetboomfamilie", false, true, null],
  ["Celtis australis", "Celtis", "Cannabaceae", true, "Europese netelboom", "Hennepfamilie", false, true, null],
  ["Celtis occidentalis", "Celtis", "Cannabaceae", true, "Zwepenboom", "Hennepfamilie", false, true, null],
  ["Larix kaempferi", "Larix", "Pinaceae", false, "Japanse larix", "Dennenfamilie", true, true, null],
  ["Gleditsia triacanthos", "Gleditsia", "Fabaceae", true, "Valse christusdoorn", "Vlinderbloemenfamilie", false, true, null],
  ["Gymnocladus dioicus", "Gymnocladus", "Fabaceae", true, "Doodsbeenderenboom", "Vlinderbloemenfamilie", false, true, null],
  ["Juglans nigra", "Juglans", "Juglandaceae", true, "Zwarte walnoot", "Okkernootfamilie", false, true, null],
  ["Juglans regia", "Juglans", "Juglandaceae", true, "Walnoot of okkernoot", "Okkernootfamilie", true, true, null],
  ["Laburnum alpinum", "Laburnum", "Fabaceae", true, "Laburnum alpinum", "Vlinderbloemenfamilie", false, true, null],
  ["Laburnum anagyroides", "Laburnum", "Fabaceae", true, "Gouden regen", "Vlinderbloemenfamilie", false, true, null],
  ["Liriodendron tulipifera", "Liriodendron", "Magnoliaceae", true, "Liriodendron tulipifera", "Tulpenboomfamilie", false, true, null],
  ["Magnolia denudata", "Magnolia", "Magnoliaceae", true, "Magnolia denudata", "Tulpenboomfamilie", false, true, null],
  ["Magnolia grandiflora", "Magnolia", "Magnoliaceae", true, "Magnolia grandiflora", "Tulpenboomfamilie", false, true, null],
  ["Magnolia kobus", "Magnolia", "Magnoliaceae", true, "Magnolia kobus", "Tulpenboomfamilie", false, true, null],
  ["Magnolia tripetala", "Magnolia", "Magnoliaceae", true, "Magnolia tripetala", "Tulpenboomfamilie", false, true, null],
  ["Metasequoia glyptostroboides", "Metasequoia", "Cupressaceae", false, "Watercipres", "Cipresfamilie", false, true, null],
  ["Picae orientalis", "Picae", "Pinaceae", false, "Kaukasische spar", "Dennenfamilie", false, true, null],
  ["Picea abies", "Picea", "Pinaceae", false, "Fijnspar", "Dennenfamilie", true, true, null],
  ["Picea omorika", "Picea", "Pinaceae", false, "Servische spar", "Dennenfamilie", true, true, null],
  ["Picea pungens", "Picea", "Pinaceae", false, "Blauwe spar", "Dennenfamilie", true, true, null],
  ["Picea sitchensis", "Picea", "Pinaceae", false, "Sitkaspar", "Dennenfamilie", true, true, null],
  ["Pinus cembra", "Pinus", "Pinaceae", false, "Alpenden", "Dennenfamilie", false, true, null],
  ["Pinus jeffreyi", "Pinus", "Pinaceae", false, "Pinus jeffreyi", "Dennenfamilie", false, true, null],
  ["Pinus mugo", "Pinus", "Pinaceae", false, "Bergden", "Dennenfamilie", false, true, null],
  ["Nothofagus antarctica", "Nothofagus", "Nothofagaceae", true, "Nothofagus antarctica", "", false, true, null],
  ["Cercidiphyllum japonicum", "Cercidiphyllum", "Cercidiphyllaceae", true, "Cercidiphyllum japonicum", "", false, true, null],
  ["Davidia involucrata", "Davidia", "Nyssaceae", true, "Vaantjesboom of zakdoekenboom", "", false, true, null],
  ["Platanus ×hispanica", "Platanus", "Platanaceae", true, "Gewone plataan", "Plataanfamilie", false, true, true],
  ["Pinus nigra", "Pinus", "Pinaceae", false, "Zwarte den", "Dennenfamilie", true, true, null],
  ["Pinus peuce", "Pinus", "Pinaceae", false, "Macedonische den", "Dennenfamilie", false, true, null],
  ["Pinus ponderosa", "Pinus", "Pinaceae", false, "Pinus ponderosa", "Dennenfamilie", false, true, null],
  ["Pinus strobus", "Pinus", "Pinaceae", false, "Weymouthden", "Dennenfamilie", true, true, null],
  ["Pinus sylvestris", "Pinus", "Pinaceae", false, "Grove den", "Dennenfamilie", true, true, null],
  ["Pinus wallichiana", "Pinus", "Pinaceae", false, "Tranenden", "Dennenfamilie", false, true, null],
  ["Platycladus orientalis", "Platycladus", "Cupressaceae", false, "Oosterse levensboom", "Cipresfamilie", false, true, null],
  ["Morus alba", "Morus", "Moraceae", true, "Witte moerbei", "Moerbeifamilie", false, true, null],
  ["Morus nigra", "Morus", "Moraceae", true, "Zwarte moerbei", "Moerbeifamilie", false, true, null],
  ["Platanus occidentalis", "Platanus", "Platanaceae", true, "Westerse plataan", "Plataanfamilie", false, true, null],
  ["Platanus orientalis", "Platanus", "Platanaceae", true, "Oosterse plataan", "Plataanfamilie", false, true, null],
  ["Acer monspessulanum", "Acer", "Sapindaceae", true, "Montpelieresdoorn", "Zeepboomfamilie", false, true, null],
  ["Acer palmatum", "Acer", "Sapindaceae", true, "Japanse esdoorn", "Zeepboomfamilie", false, true, null],
  ["Acer pensylvanicum", "Acer", "Sapindaceae", true, "striped maple", "Zeepboomfamilie", false, true, null],
  ["Acer platanoides", "Acer", "Sapindaceae", true, "Noorse esdoorn", "Zeepboomfamilie", true, true, null],
  ["Acer pseudoplatanus", "Acer", "Sapindaceae", true, "Gewone esdoorn", "Zeepboomfamilie", true, true, null],
  ["Acer rubrum", "Acer", "Sapindaceae", true, "Rode esdoorn", "Zeepboomfamilie", false, true, null],
  ["Acer saccharinum", "Acer", "Sapindaceae", true, "Witte esdoorn of zilveresdoorn", "Zeepboomfamilie", false, true, null],
  ["Acer saccharum", "Acer", "Sapindaceae", true, "Suikeresdoorn", "Zeepboomfamilie", false, true, null],
  ["Acer tataricum", "Acer", "Sapindaceae", true, "Tartaarse esdoorn", "Zeepboomfamilie", false, true, null],
  ["Aesculus hippocastanum", "Aesculus", "Sapindaceae", true, "Witte paardenkastanje", "Zeepboomfamilie", true, true, null],
  ["Aesculus flava", "Aesculus", "Sapindaceae", true, "yellow buckeye", "Zeepboomfamilie", false, true, null],
  ["Fraxinus americana", "Fraxinus", "Oleaceae", true, "white ash", "Olijffamilie", false, true, null],
  ["Fraxinus angustifolia", "Fraxinus", "Oleaceae", true, "Smalbladige es", "Olijffamilie", false, true, null],
  ["Fraxinus ornus", "Fraxinus", "Oleaceae", true, "Pluimes", "Olijffamilie", false, true, null],
  ["Fraxinus pennsylvanica", "Fraxinus", "Oleaceae", true, "green ash", "Olijffamilie", false, true, null],
  ["Hippophae rhamnoides", "Hippophae", "Elaeagnaceae", true, "Duindoorn", "Duindoornfamilie", true, false, null],
  ["Koelreuteria paniculata", "Koelreuteria", "Sapindaceae", true, "Chinese vernisboom of lampionboom", "Zeepboomfamilie", false, true, null],
  ["Ligustrum vulgare", "Ligustrum", "Oleaceae", true, "wilde liguster", "Olijffamilie", true, false, null],
  ["Malus angustifolia", "Malus", "Rosaceae", true, "southern crabapple", "Rozenfamilie", false, true, null],
  ["Malus asiatica", "Malus", "Rosaceae", true, "Chinese pearleaf crabapple", "Rozenfamilie", false, true, null],
  ["Malus baccata ", "Malus", "Rosaceae", true, "Siberian crabapple", "Rozenfamilie", false, true, null],
  ["Malus brevipes", "Malus", "Rosaceae", true, "shrub apple", "Rozenfamilie", false, true, null],
  ["Malus coronaria", "Malus", "Rosaceae", true, "Sweet crabapple", "Rozenfamilie", false, true, null],
  ["Malus domestica", "Malus", "Rosaceae", true, "Appel", "Rozenfamilie", false, true, null],
  ["Malus doumeri", "Malus", "Rosaceae", true, "Taiwan crabapple", "Rozenfamilie", false, true, null],
  ["Aesculus  carnea", "Aesculus", "Sapindaceae", true, "Rode paardenkastanje", "Zeepboomfamilie", false, true, null],
  ["Abies alba", "Abies", "Pinaceae", false, "Zilverspar", "Dennenfamilie", true, true, null],
  ["Abies cephalonica", "Abies", "Pinaceae", false, "Griekse zilverspar", "Dennenfamilie", false, true, null],
  ["Abies concolor", "Abies", "Pinaceae", false, "Colorado-zilverspar", "Dennenfamilie", false, true, null],
  ["Zelkova serrata", "Zelkova", "Ulmaceae", true, "Japanse zelkova", "Iepenfamilie", false, true, null],
  ["Ceratonia siliqua", "Ceratonia", "Fabaceae", true, "Johannesbroodboom", "Vlinderbloemenfamilie", false, true, null],
  ["Cercis siliquastrum", "Cercis", "Fabaceae", true, "Judasboom", "Vlinderbloemenfamilie", false, true, null],
  ["Cornus controversa", "Cornus", "Cornaceae", true, "wedding cake tree", "Kornoeljefamilie", null, null, null],
  ["Cornus kousa", "Cornus", "Cornaceae", true, "kousa dogwood", "Kornoeljefamilie", null, null, null],
  ["Cornus mas", "Cornus", "Cornaceae", true, "Gele kornoelje", "Kornoeljefamilie", true, true, null],
  ["Cornus nuttallii", "Cornus", "Cornaceae", true, "Pacific dogwood", "Kornoeljefamilie", null, null, null],
  ["Cornus sanguinea", "Cornus", "Cornaceae", true, "Rode kornoelje", "Kornoeljefamilie", true, true, null],
  ["Corylus avellana", "Corylus", "Betulaceae", true, "Hazelaar", "Berkenfamilie", true, true, null],
  ["Corylus colurna", "Corylus", "Betulaceae", true, "Boomhazelaar of Turkse hazelaar", "Berkenfamilie", false, true, null],
  ["Corylus maxima", "Corylus", "Betulaceae", true, "Lambertsnoot of lambertusnoot", "Berkenfamilie", false, true, null],
  ["Chamaecyparis lawsoniana", "Chamaecyparis", "Cupressaceae", false, "Californische cipres", "Cipresfamilie", false, true, null],
  ["Chamaecyparis nootkatensis", "Chamaecyparis", "Cupressaceae", false, "Nootkacipres", "Cipresfamilie", false, true, null],
  ["Chamaecyparis pisifera", "Chamaecyparis", "Cupressaceae", false, "Chamaecyparis pisifera", "Cipresfamilie", false, true, null],
  ["Cryptomeria japonica", "Cryptomeria", "Cupressaceae", false, "Japanse ceder", "Cipresfamilie", false, true, null],
  ["Cupressus macrocarpa", "Cupressus", "Cupressaceae", false, "Montereycipres", "Cipresfamilie", false, true, null],
  ["Cupressus sempervirens", "Cupressus", "Cupressaceae", false, "Italiaanse cipres", "Cipresfamilie", false, true, null],
  ["Fagus grandifolia", "Fagus", "Fagaceae", true, "American beech", "Napjesdragersfamilie", false, true, null],
  ["Fagus orientalis", "Fagus", "Fagaceae", true, "Oosterse beuk of Kaukasische beuk", "Napjesdragersfamilie", false, true, null],
  ["Fagus sylvatica", "Fagus", "Fagaceae", true, "Beuk", "Napjesdragersfamilie", true, true, null],
  ["Ficus carica", "Ficus", "Moraceae", true, "Vijgenboom", "Moerbeifamilie", false, true, null],
  ["Other tree", "Other", "XXXXXXXXXX", true, "Andere boom", "", null, true, null],
  ["Salix syrticola", "Salix", "Salicaceae", true, "Salix syrticola", "Wilgenfamilie", true, true, null],
  ["Salix triandra", "Salix", "Salicaceae", true, "Amandelwilg", "Wilgenfamilie", false, true, null],
  ["Salix viminalis", "Salix", "Salicaceae", true, "Katwilg", "Wilgenfamilie", true, true, null],
  ["Sorbus aria", "Sorbus", "Rosaceae", true, "Meelbes", "Rozenfamilie", false, true, null],
  ["Sorbus aucuparia", "Sorbus", "Rosaceae", true, "Wilde lijsterbes", "Rozenfamilie", true, true, null],
  ["Sorbus hybrida", "Sorbus", "Rosaceae", true, "Finse meelbes", "Rozenfamilie", null, null, null],
  ["Sorbus intermedia", "Sorbus", "Rosaceae", true, "Zweedse lijsterbes", "Rozenfamilie", false, true, null],
  ["Sorbus latifolia ", "Sorbus", "Rosaceae", true, "broad-leaved whitebeam", "Rozenfamilie", false, true, null],
  ["Sorbus torminalis", "Sorbus", "Rosaceae", true, "Elsbes", "Rozenfamilie", false, true, null],
  ["Prunus insititia ", "Prunus", "Rosaceae", true, "Mirabel", "Rozenfamilie", false, true, null],
  ["Prunus laurocerasus", "Prunus", "Rosaceae", true, "Laurierkers", "Rozenfamilie", false, true, null],
  ["Prunus maackii ", "Prunus", "Rosaceae", true, "Mantsjoerijse kers", "Rozenfamilie", false, true, null],
  ["Prunus mahaleb", "Prunus", "Rosaceae", true, "Weichselboom", "Rozenfamilie", false, true, null],
  ["Prunus 'mahogany lustre'", "Prunus", "Rosaceae", true, "Prunus 'Mahogany Lustre'", "Rozenfamilie", null, true, null],
  ["Prunus padus", "Prunus", "Rosaceae", true, "Vogelkers", "Rozenfamilie", true, false, null],
  ["Sorbus ×arnoldiana", "Sorbus", "Rosaceae", true, "Schouten Lijsterbes", "Rozenfamilie", null, true, true],
  ["Sorbus ×thuringiaca", "Sorbus", "Rosaceae", true, "gedeelde meelbes", "Rozenfamilie", null, true, true],
  ["Prunus ×gondouinii 'schnee'", "Prunus", "Rosaceae", true, "Prunus 'Schnee'", "Rozenfamilie", null, true, true],
  ["Prunus ×hillieri ", "Prunus", "Rosaceae", true, "Prunus Spire", "Rozenfamilie", null, true, true],
  ["Prunus salicina ×armeniaca ", "Prunus", "Rosaceae", true, "Pluot", "Rozenfamilie", false, true, true],
  ["Pyrus ×canescens", "Pyrus", "Juglandaceae", true, "South African Pear", "Okkernootfamilie", false, true, true],
  ["Prunus ×schmitti", "Prunus", "Rosaceae", true, "Prunus Schmitti", "Rozenfamilie", null, true, true],
  ["Tilia ×europea", "Tilia", "Malvaceae", true, "Krimlinde", "Kaasjeskruidfamilie", false, true, true],
  ["Prunus  ×yedoensis", "Prunus", "Rosaceae", true, "Prunus yedoensis", "Rozenfamilie", false, true, true],
  ["Pseudotsuga menzoiesii", "Pseudotsuga", "Pinaceae", false, "Douglasspar", "Dennenfamilie", true, true, null],
  ["Pterocarya fraxinifolia", "Pterocarya", "Juglandaceae", true, "Kaukasische vleugelnoot", "Okkernootfamilie", false, true, null],
  ["Pterocarya stenoptera", "Pterocarya", "Juglandaceae", true, "Chinese wingnut", "Okkernootfamilie", false, true, null],
  ["Pyrus calleryana", "Pyrus", "Juglandaceae", true, "Callery pear", "Okkernootfamilie", false, true, null],
  ["Pyrus salicifolia 'pendula'", "Pyrus", "Juglandaceae", true, "wilgbladige_peer", "Okkernootfamilie", null, true, null],
  ["Quercus bicolor", "Quercus", "Fagaceae", true, "Tweekleurige eik", "Napjesdragersfamilie", false, true, null],
  ["Quercus castaneifolia", "Quercus", "Fagaceae", true, "chestnut-leaved oak", "Napjesdragersfamilie", false, true, null],
  ["Thuja plicata", "Thuja", "Cupressaceae", false, "Reuzenlevensboom", "Cipresfamilie", false, true, null],
  ["Thujopsis dolabrata", "Thujopsis", "Cupressaceae", false, "Hibacipres", "Cipresfamilie", false, true, null],
  ["Tsuga canadensis", "Tsuga", "Pinaceae", false, "Oosterse hemlockspar, oostelijke hemlockspar of Canadese hemlockspar", "Dennenfamilie", false, true, null],
  ["Tsuga heterophylla", "Tsuga", "Pinaceae", false, "Westerse hemlockspar of westerse hemlockspar", "Dennenfamilie", true, true, null],
  ["Sambucus nigra", "Sambucus", "Adoxaceae", true, "Gewone vlier", "Muskuskruidfamilie", true, false, null],
  ["Sophora japonica", "Sophora", "Fabaceae", true, "Honingboom", "Vlinderbloemenfamilie", false, true, null],
  ["Tilia americana", "Tilia", "Malvaceae", true, "Amerikaanse linde", "Kaasjeskruidfamilie", false, true, null],
  ["Tilia cordata", "Tilia", "Malvaceae", true, "Winterlinde of kleinbladige linde", "Kaasjeskruidfamilie", true, true, null],
  ["Prunus sargentii", "Prunus", "Rosaceae", true, "Sargent's cherry", "Rozenfamilie", false, true, null],
  ["Prunus serotina", "Prunus", "Rosaceae", true, "Amerikaanse vogelkers", "Rozenfamilie", true, true, null],
  ["Prunus serrulata", "Prunus", "Rosaceae", true, "Japanse sierkers", "Rozenfamilie", false, true, null],
  ["Tilia mongolica", "Tilia", "Malvaceae", true, "Mongolian lime", "Kaasjeskruidfamilie", false, true, null],
  ["Prunus sibirica ", "Prunus", "Rosaceae", true, "Siberische vogelkers", "Rozenfamilie", false, true, null],
  ["Prunus spinosa", "Prunus", "Rosaceae", true, "sleedoorn", "Rozenfamilie", true, false, null],
  ["Prunus subhirtella ", "Prunus", "Rosaceae", true, "Winterbloeiende kers", "Rozenfamilie", false, true, null],
  ["Prunus 'umineko'", "Prunus", "Rosaceae", true, "Chinese kers", "Rozenfamilie", false, true, null],
  ["Tilia platyphyllos", "Tilia", "Malvaceae", true, "Zomerlinde of grootbladige linde", "Kaasjeskruidfamilie", true, true, null],
  ["Pyrus communis", "Pyrus", "Rosaceae", true, "Peer", "Rozenfamilie", true, true, null],
  ["Quercus ×hispanica", "Quercus", "Fagaceae", true, "Spanish oak", "Napjesdragersfamilie", false, true, true],
  ["Quercus ×turneri", "Quercus", "Fagaceae", true, "", "Napjesdragersfamilie", false, true, true],
  ["Robinia  ×margaretta 'casque rouge'", "Robinia", "Fagaceae", true, "Pink Cascade", "Napjesdragersfamilie", null, true, true],
  ["Sciadopitys verticillata", "Sciadopitys", "Sciadopityaceae", false, "Japanse parasolden", "", false, true, null],
  ["Ribes nigra", "Ribes", "Grossulariaceae", true, "zwarte bes", "Ribesfamilie", true, false, null],
  ["Quercus cerris", "Quercus", "Fagaceae", true, "Moseik of Turkse eik", "Napjesdragersfamilie", false, true, null],
  ["Quercus coccinea", "Quercus", "Fagaceae", true, "Scharlaken eik", "Napjesdragersfamilie", false, true, null],
  ["Quercus frainetto", "Quercus", "Fagaceae", true, "Hongaarse eik", "Napjesdragersfamilie", false, true, null],
  ["Quercus ilex", "Quercus", "Fagaceae", true, "Steeneik", "Napjesdragersfamilie", false, true, null],
  ["Quercus macranthera", "Quercus", "Fagaceae", true, "Perzische eik", "Napjesdragersfamilie", false, true, null],
  ["Quercus palustris", "Quercus", "Fagaceae", true, "Moeraseik", "Napjesdragersfamilie", false, true, null],
  ["Quercus petraea", "Quercus", "Fagaceae", true, "Wintereik[4]", "Napjesdragersfamilie", true, true, null],
  ["Quercus phellos", "Quercus", "Fagaceae", true, "willow oak", "Napjesdragersfamilie", false, true, null],
  ["Quercus robur", "Quercus", "Fagaceae", true, "Zomereik[4]", "Napjesdragersfamilie", true, true, null],
  ["Quercus rubra", "Quercus", "Fagaceae", true, "Amerikaanse eik", "Napjesdragersfamilie", true, true, null],
  ["Rhododendron ponticum", "Rhododendron", "Ericaceae", false, "pontische rhododendron", "Heidefamilie", true, false, null],
  ["Robinia pseudoacacia", "Robinia", "Fabaceae", true, "Robinia, valse acacia of witte acacia", "Vlinderbloemenfamilie", true, true, null],
  ["Robinia viscosa", "Robinia", "Fabaceae", true, "clammy locust", "Vlinderbloemenfamilie", false, true, null],
  ["Sequoiadendron giganteum", "Sequoiadendron", "Cupressaceae", false, "Mammoetboom of reuzensequoia", "Cipresfamilie", false, true, null],
  ["Taxodium distichum", "Taxodium", "Cupressaceae", false, "Moerascipres", "Cipresfamilie", false, true, null],
  ["Taxus baccata", "Taxus", "Taxaceae", false, "Taxus of venijnboom", "Taxusfamilie", true, true, null],
  ["Thuja occidentalis", "Thuja", "Cupressaceae", false, "Westerse levensboom", "Cipresfamilie", false, true, null],
  ["Viburnum opulus", "Viburnum", "Adoxaceae", true, "gelderse roos", "muskuskruidfamilie", null, false, null],
  ["Tilia tomentosa", "Tilia", "Malvaceae", true, "Zilverlinde", "Kaasjeskruidfamilie", false, true, null],
  ["Ulmus 'columella'", "Ulmus", "Ulmaceae", true, "Columella", "Iepenfamilie", null, true, null],
  ["Ulmus glabra", "Ulmus", "Ulmaceae", true, "Ruwe iep", "Iepenfamilie", false, true, null],
  ["Ulmus laevis", "Ulmus", "Ulmaceae", true, "Steeliep of fladderiep", "Iepenfamilie", true, true, null],
  ["Ulmus 'lobel'", "Ulmus", "Ulmaceae", true, "Lobel", "Iepenfamilie", null, true, null],
  ["Ulmus minor", "Ulmus", "Ulmaceae", true, "Gladde iep", "Iepenfamilie", true, true, null],
  ["Ulmus 'plantyn'", "Ulmus", "Ulmaceae", true, "Plantijn, Plantyn", "Iepenfamilie", null, true, null],
  ["Zelkova carpinifolia", "Zelkova", "Ulmaceae", true, "Zwepenboom of Kaukasische schijniep", "Iepenfamilie", false, true, null],
  ["Cupressus ×leylandii", "Cupressus", "Cupressaceae", false, "Leylandcipres", "Cipresfamilie", false, true, true],
  ["Ostrya Carpinifolia", "Ostrya", "Betulaceae", true, "Europese hopbeuk", "Berkenfamilie", false, true, null],
  ["Buxus sempervirens", "Buxus", "Buxaceae", false, "Buxus", "Buxusfamilie", true, false, null],
  ["Kalopanax septemlobus", "Kalopanax", "Araliaceae", true, "Stekelboom", "Klimopfamilie", false, true, null],
  ["Tetradium daniellii", "Tetradium", "Rutaceae", true, "Bijenboom", "Wijnruitfamilie", false, true, null],
  ["Rhus typhina", "Rhus", "Anacardiaceae", true, "Fluweelboom", "Pruikenboomfamilie", false, true, null],
  ["Rhus glabra", "Rhus", "Anacardiaceae", true, "Fluweelboom", "Pruikenboomfamilie", false, true, null],
  ["Cotoneaster dielsianus", "Cotoneaster", "Rosaceae", true, "Dwergmispel", "Rozenfamilie", false, false, null],
  ["Heptacodium miconioides", "Heptacodium", "Caprifoliaceae", true, "Zevenzonenboom", "Kamperfoeliefamilie", false, true, null],
  ["Cladrastis kentukea", "Cladrastis", "Fabaceae", true, "Geelhout", "Vlinderbloemenfamilie", false, true, null],
  ["Clerodendrum trichotomum", "Clerodendrum", "Lamiaceae", true, "Pindakaasboom", "Lipbloemenfamilie", false, false, null],
  ["Phellodendron amurense", "Phellodendron", "Rutaceae", true, "Amur kurkboom", "Wijnruitfamilie", false, true, null],
  ["Syringa vulgaris", "Syringa", "Oleaceae", true, "Sering", "Olijffamilie", true, false, null],
  ["Halesia monticola", "Halesia", "Styracaceae", true, "Sneeuwklokjesboom", "Styracaceae", false, false, null],
  ["Nyssa sylvatica", "Nyssa", "Nyssaceae", true, "Zwarte tupeloboom", "Nyssaceae", false, true, null],
  ["Aralia elata", "Aralia", "Araliaceae", true, "Engelenboom", "Klimopfamilie", false, false, null],
  ["Broussonetia papyrifera", "Broussonetia", "Moraceae", true, "Papiermoerbei", "Moerbeifamilie", false, true, null],
  ["Pyracantha", "Pyracantha", "Rosaceae", false, "Vuurdoorn", "Rozenfamilie", false, false, null],
  ["Chamaecyparis", "Chamaecyparis", "Cupressaceae", false, "", "Cipresfamilie", true, true, null],
  ["Photinia fraseri 'Red Robin'", "Photinia", "Rosaceae", false, "Glansmispel", "Rozenfamilie", false, false, null],
  ["Tilia europaea", "Tilia europaea", "Malvaceae", true, "Hollandse linde", "Kaasjeskruidfamilie", false, true, null],
  ["Tilia vulgaris", "Tilia vulgaris", "Malvaceae", true, "Hollandse linde", "Kaasjeskruidfamilie", false, true, null],
  ["Ulmus ×hollandica", "Ulmus", "Ulmaceae", true, "Hollandse iep", "Iepenfamilie", false, true, true],
  ["+Laburnocytisus 'Adamii'", "+Laburnocytisus", "Fabaceae", true, "Adam's goudenregen", "Vlinderbloemenfamilie", true, true, null],
  ["Amelanchier lamarckii", "Amelanchier", "Rosaceae", true, "Amerikaans krentenboompje", "Rozenfamilie", false, false, null],
  ["Cupressocyparis ×leylandii", "Cupressocyparis", "Cupressaceae", false, "Leylandcipres", "Cipresfamilie", false, true, true],
  ["Alangium platanifolium genuinum", "Alangium", "Cornaceae", true, "Alangium", "Kornoeljefamilie", false, true, null],
  ["Asimina triloba", "Asimina", "Annonaceae", true, "Pawpaw", "Annonaceae", false, true, false],
  ["Aucuba japonica `Variegata`", "Aucuba", "Garryaceae", true, "Broodboom", "Garryaceae", false, false, false],
  ["Berberis julianae", "Berberis", "Berberidaceae", true, "Zuurbes", "Berberisfamilie", true, false, null],
  ["Berberis ×lologensis", "Berberis", "Berberidaceae", true, "Zuurbes", "Berberisfamilie", true, false, true],
  ["Caragana arborescens `Pendula`", "Caragana", "Fabaceae", true, "Erwtenstruik", "Vlinderbloemenfamilie", true, true, null],
  ["Ceanothus `Blue Mound`", "Ceanothus", "Rhamnaceae", true, "amerikaanse sering", "Wegedoornfamilie", false, false, null],
  ["Ceanothus griseus `Yankee Point`", "Ceanothus", "Rhamnaceae", true, "amerikaanse sering", "Wegedoornfamilie", false, false, null],
  ["Chaenomeles ×superba `Fascination`", "Chaenomeles", "Rosaceae", true, "sierkwee", "Rozenfamilie", false, false, true],
  ["Chaenomeles ×superba `Hollandia`", "Chaenomeles", "Rosaceae", true, "sierkwee", "Rozenfamilie", false, false, true],
  ["Chimonanthus praecox", "Chimonanthus", "Calycanthaceae", true, "meloenboompje", "Calycanthaceae", false, false, false],
  ["Chimonanthus praecox `Concolor`", "Chimonanthus", "Calycanthaceae", true, "meloenboompje", "Calycanthaceae", false, false, null],
  ["Chionanthus retusus", "Chionanthus", "Oleaceae", true, "Sneeuwvlokkenboom", "olijffamilie", false, true, false],
  ["Chionanthus virginicus", "Chionanthus", "Oleaceae", true, "Sneeuwvlokkenboom", "olijffamilie", false, true, false],
  ["×Chitalpa tashkentensis", "Chitalpa", "Bignoniaceae", true, "Chitalpa", "Trompetboomfamilie", false, false, true],
  ["×Choisya `Aztec Pearl`", "Choisya", "Rutaceae", false, "Choisya", "Wijnruitfamilie", false, false, true],
  ["Clethra alnifolia `Ruby Spice`", "Clethra", "Clethraceae", true, "Schijnels", "Clethraceae", false, false, false],
  ["Clethra barbinervis", "Clethra", "Clethraceae", true, "Schijnels", "Clethraceae", false, false, false],
  ["Corylopsis pauciflora", "Corylopsis", "Hamamelidaceae", true, "Schijnhazelaar", "Toverhazelaarfamilie", false, false, false],
  ["Corylopsis spicata", "Corylopsis", "Hamamelidaceae", true, "Schijnhazelaar", "Toverhazelaarfamilie", false, false, false],
  ["Cotinus coggygria", "Cotinus", "Anacardiaceae", true, "Pruikenboom", "Pruikenboomfamilie", true, true, false],
  ["×Crataemespilus grandiflora", "×Crataemespilus", "Rosaceae", true, "Meidoornmispel", "Rozenfamilie", true, true, true],
  ["Cudrania tricuspidata", "Cudrania", "Moraceae", true, "Cudrania", "Moerbeifamilie", false, true, false],
  ["Cunninghamia lanceolata", "Cunninghamia", "Cupressaceae", false, "Spiesden", "Cipresfamilie", false, true, false],
  ["Cupressocyparis ×leylandii `Castlewellan`", "Cupressocyparis", "Cupressaceae", false, "Leylandcipres", "Cipresfamilie", true, true, true],
  ["Cyclocarya paliurus", "Cyclocarya", "Juglandaceae", true, "Cyclocarya", "Okkernootfamilie", false, true, false],
  ["Diervilla ×splendens", "Diervilla", "Caprifoliaceae", true, "Diervilla", "Kamperfoeliefamilie", false, false, true],
  ["Diospyros kaki", "Diospyros", "Ebenaceae", true, "Kaki", "Ebenaceae", false, true, false],
  ["Diospyros lotus", "Diospyros", "Ebenaceae", true, "Lotus", "Ebenaceae", true, true, false],
  ["Diospyros virginiana", "Diospyros", "Ebenaceae", true, "Amerikaanse persimoen", "Ebenaceae", false, true, false],
  ["Dipelta ventricosa", "Dipelta", "Caprifoliaceae", true, "Dipelta", "Kamperfoeliefamilie", false, false, false],
  ["Disanthus cercidifolius", "Disanthus", "Hamamelidaceae", true, "Disanthus", "Toverhazelaarfamilie", false, false, false],
  ["Edgeworthia chrysantha", "Edgeworthia", "Thymelaeceae", true, "Edgeworthia", "Peperboompjesfamilie", false, false, false],
  ["Eleutherococcus sieboldianus", "Eleutherococcus", "Araliaceae", true, "Eleutherococcus", "Klimopfamilie", false, true, false],
  ["Emmenopterys henryi", "Emmenopterys", "Rubiaceae", true, "Emmenopterys", "Sterbladigenfamilie", false, true, false],
  ["Escallonia `Apple Blossom`", "Escallonia", "Escalloniaceae", true, "Escallonia", "Escalloniaceae", false, false, null],
  ["Eucommia ulmoides", "Eucommia", "Eucommiaceae", true, "Iepbladige gummiboom", "Eucommiaceae", false, true, false],
  ["Euonymus europaeus", "Euonymus", "Celastraceae", true, "Wilde kardinaalsmuts", "Kardinaalsmutsfamilie", true, false, false],
  ["Euonymus grandiflorus", "Euonymus", "Celastraceae", true, "Kardinaalsmuts", "Kardinaalsmutsfamilie", false, false, false],
  ["Euonymus grandiflorus `Red Wine`", "Euonymus", "Celastraceae", true, "Kardinaalsmuts", "Kardinaalsmutsfamilie", false, false, false],
  ["Euptelea polyandra", "Euptelea", "Eupteleaceae", true, "Euptelea", "Eupteleaceae", false, true, false],
  ["Exochorda serratifolia `Snow White`", "Exochorda", "Rosaceae", true, "Parelstruik", "Rozenfamilie", false, false, null],
  ["Fothergilla major", "Fothergilla", "Hamamelidaceae", true, "lampenpoetserstruik ", "Toverhazelaarfamilie", false, false, false],
  ["Frangula alnus", "Frangula", "Rhamnaceae", true, "Sporkehout", "Wegedoornfamilie", true, false, false],
  ["Hamamelis japonica `Zuccariniana`", "Hamamelis", "Hamamelidaceae", true, "Japanse toverhazelaar", "Toverhazelaarfamilie", false, false, false],
  ["Hamamelis mollis", "Hamamelis", "Hamamelidaceae", true, "Chinese toverhazelaar", "Toverhazelaarfamilie", false, false, false],
  ["Hibiscus", "Hibiscus", "Malvaceae", true, "Hibiscus", "Kaasjeskruidfamilie", false, false, null],
  ["Hibiscus syriacus", "Hibiscus", "Malvaceae", true, "Altheastruik", "Kaasjeskruidfamilie", false, false, null],
  ["Hibiscus syriacus `Coelestis`", "Hibiscus", "Malvaceae", true, "Altheastruik", "Kaasjeskruidfamilie", false, false, null],
  ["Hibiscus syriacus `Woodbridge`", "Hibiscus", "Malvaceae", true, "Altheastruik", "Kaasjeskruidfamilie", false, false, null],
  ["Hydrangea macrophylla `Bodensee`", "Hydrangea", "Hydrangeaceae", true, "Tuinhortensia", "Hortensiafamilie", false, false, false],
  ["Hydrangea macrophylla `Madame Emile MouillÞre`", "Hydrangea", "Hydrangeaceae", true, "Tuinhortensia", "Hortensiafamilie", false, false, false],
  ["Hydrangea macrophylla `Merveille Sanguinea`", "Hydrangea", "Hydrangeaceae", true, "Tuinhortensia", "Hortensiafamilie", false, false, false],
  ["Hydrangea paniculata `Floribunda`", "Hydrangea", "Hydrangeaceae", true, "Pluimhortensia", "Hortensiafamilie", false, false, false],
  ["Hydrangea paniculata `Limelight`", "Hydrangea", "Hydrangeaceae", true, "Pluimhortensia", "Hortensiafamilie", false, false, false],
  ["Hydrangea paniculata `Wim`s Red`", "Hydrangea", "Hydrangeaceae", true, "Pluimhortensia", "Hortensiafamilie", false, false, false],
  ["Hydrangea quercifolia", "Hydrangea", "Hydrangeaceae", true, "Eikenbladhortensia", "Hortensiafamilie", false, false, false],
  ["Hydrangea quercifolia `Flemygea`", "Hydrangea", "Hydrangeaceae", true, "Eikenbladhortensia", "Hortensiafamilie", false, false, false],
  ["Idesia polycarpa", "Idesia", "Salicaceae", true, "Oranjekers", "Wilgenfamilie", false, true, false],
  ["Itea virginica `Henry`s Garnet`", "Itea", "Iteaceae", true, "Itea", "Iteaceae", false, false, true],
  ["Kolkwitzia amabilis", "Kolkwitzia", "Caprifoliaceae", true, "Kolkwitzia", "Kamperfoeliefamilie", false, false, false],
  ["Lagerstroemia indica", "Lagerstroemia", "Lythraceae", true, "Lagerstroemia", "Kattenstaartfamilie", false, true, false],
  ["Lespedeza thunbergii", "Lespedeza", "Fabaceae", true, "Lespedeza", "Vlinderbloemfamilie", false, false, false],
  ["Leucothoe `Zeblid`", "Leucothoe", "Ericaceae", false, "Druifheide", "Heidefamilie", false, false, false],
  ["Leucothoe axillaris `Curly Red`", "Leucothoe", "Ericaceae", false, "Druifheide", "Heidefamilie", false, false, false],
  ["Leucothoe fontanesiana", "Leucothoe", "Ericaceae", false, "Druifheide", "Heidefamilie", false, false, false],
  ["Leycesteria formosa", "Leycesteria", "Caprifoliaceae", true, "Fazantenbes", "Kamperfoeliefamilie", false, false, false],
  ["Lonicera tatarica", "Lonicera", "Caprifoliaceae", true, "Kamperfoelie", "Kamperfoeliefamilie", false, false, false],
  ["Maackia amurensis", "Maackia", "Fabaceae", true, "Maackia", "Vlinderbloemfamilie", false, true, false],
  ["Maackia chinensis", "Maackia", "Fabaceae", true, "Maackia", "Vlinderbloemfamilie", false, true, false],
  ["Maddenia hypoleuca", "Maddenia", "Rosaceae", true, "Maddenia", "Rozenfamilie", false, true, false],
  ["Mahonia aquifolium `Apollo`", "Mahonia", "Berberidaceae", true, "Mahonia", "Berberisfamilie", false, false, false],
  ["Mahonia japonica", "Mahonia", "Berberidaceae", true, "Mahonia", "Berberisfamilie", false, false, false],
  ["Meliosma beaniana", "Meliosma", "Sabiaceae", true, "Meliosma", "Sabiaceae", false, true, false],
  ["Nandina domestica", "Nandina", "Berberidaceae", false, "Nandina", "Berberisfamilie", false, true, false],
  ["Oemleria cerasiformis", "Oemleria", "Rosaceae", true, "Oemleria", "Rozenfamilie", false, false, false],
  ["Osmanthus ×burkwoodii", "Osmanthus", "Oleaceae", false, "Schijnhulst", "olijffamilie", false, false, true],
  ["Osmanthus heterophyllus", "Osmanthus", "Oleaceae", false, "Schijnhulst", "olijffamilie", false, false, false],
  ["Oxydendrum arboreum", "Oxydendrum", "Ericaceae", true, "Zuurboom", "Heidefamilie", false, true, false],
  ["Parrotiopsis jacquemontiana", "Parrotiopsis", "Hamamelidaceae", true, "Parrotiopsis", "Toverhazelaarfamilie", false, true, false],
  ["Philadelphus `Bouquet Blanc`", "Philadelphus", "Hydrangeaceae", true, "Boerenjasmijn", "Hortensiafamilie", false, false, false],
  ["Philadelphus `Dame Blanche`", "Philadelphus", "Hydrangeaceae", true, "Boerenjasmijn", "Hortensiafamilie", false, false, false],
  ["Philadelphus `Lemoinei`", "Philadelphus", "Hydrangeaceae", true, "Boerenjasmijn", "Hortensiafamilie", false, false, false],
  ["Physocarpus opulifolius `Diabolo`", "Physocarpus", "Rosaceae", true, "Blaasspirea", "Rozenfamilie", false, false, false],
  ["Picrasma quassioides", "Picrasma", "Simaroubaceae", true, "Picrasma", "Hemelboomfamilie", false, true, false],
  ["Podocarpus `Fastigiata`", "Podocarpus", "Podocarpaceae", false, "Podocarpus", "Podocarpaceae", false, false, null],
  ["Podocarpus `Maori Prince`", "Podocarpus", "Podocarpaceae", false, "Podocarpus", "Podocarpaceae", false, false, null],
  ["Podocarpus `Redtip`", "Podocarpus", "Podocarpaceae", false, "Podocarpus", "Podocarpaceae", false, false, false],
  ["Podocarpus acutifolius", "Podocarpus", "Podocarpaceae", false, "Podocarpus", "Podocarpaceae", false, true, null],
  ["Podocarpus lawrencei `Blue Gem`", "Podocarpus", "Podocarpaceae", false, "Podocarpus", "Podocarpaceae", false, true, null],
  ["Podocarpus macrophyllus", "Podocarpus", "Podocarpaceae", false, "Podocarpus", "Podocarpaceae", false, true, false],
  ["Podocarpus nivalis", "Podocarpus", "Podocarpaceae", false, "Podocarpus", "Podocarpaceae", false, false, false],
  ["Podocarpus nivalis `Kralingen`", "Podocarpus", "Podocarpaceae", false, "Podocarpus", "Podocarpaceae", false, false, null],
  ["Podocarpus nivalis `Trompenburg`", "Podocarpus", "Podocarpaceae", false, "Podocarpus", "Podocarpaceae", false, false, null],
  ["Podocarpus nubigenus", "Podocarpus", "Podocarpaceae", false, "Podocarpus", "Podocarpaceae", false, true, null],
  ["Podocarpus totara `Pendulus`", "Podocarpus", "Podocarpaceae", false, "Podocarpus", "Podocarpaceae", false, true, null],
  ["Poncirus trifoliata", "Poncirus", "Rutaceae", true, "Wilde citroen", "Wijnruitfamilie", false, true, false],
  ["Pseudopanax laetus", "Pseudopanax", "Araliaceae", false, "Pseudopanax", "Klimopfamilie", false, false, false],
  ["Ptelea trifoliata", "Ptelea", "Rutaceae", true, "Lederboom", "Wijnruitfamilie", false, true, false],
  ["Pterostyrax corymbosa", "Pterostyrax", "Styracaceae", true, "Pterostyrax", "Styracaceae", false, true, false],
  ["Pterostyrax hispida", "Pterostyrax", "Styracaceae", true, "Pterostyrax", "Styracaceae", false, true, false],
  ["Rosa pimpinellifolia", "Rosa", "Rosaceae", true, "Duinroos", "Rozenfamilie", true, false, false],
  ["Sarcococca hookeriana", "Sarcococca", "Buxaceae", false, "Sarcococca", "Buxusfamilie", false, false, false],
  ["Sassafras albidum", "Sassafras", "Lauraceae", true, "Sassafras", "Laurierfamilie", false, true, false],
  ["Sequoia sempervirens", "Sequoia", "Cupressaceae", false, "Kustmammoetboom", "Cipresfamilie", false, true, false],
  ["Skimmia japonica `Moerings 1`", "Skimmia", "Rutaceae", false, "Skimmia", "Wijnruitfamilie", false, false, false],
  ["Staphylea colchica", "Staphylea", "Staphyleaceae", true, "Pimpernoot", "Pimpernootfamilie", false, true, false],
  ["Staphylea pinnata", "Staphylea", "Staphyleaceae", true, "Pimpernoot", "Pimpernootfamilie", false, true, false],
  ["Stewartia monadelpha", "Stewartia", "Theaceae", true, "Stewartia", "Theaceae", false, true, false],
  ["Stewartia pseudocamellia", "Stewartia", "Theaceae", true, "Stewartia", "Theaceae", false, true, false],
  ["Stewartia rostrata", "Stewartia", "Theaceae", true, "Stewartia", "Theaceae", false, true, false],
  ["Stewartia sinensis", "Stewartia", "Theaceae", true, "Stewartia", "Theaceae", false, true, false],
  ["Styphnolobium japonicum", "Styphnolobium", "Fabaceae", true, "Honingboom", "Vlinderbloemfamilie", false, true, false],
  ["Styphnolobium japonicum `Fleright`", "Styphnolobium", "Fabaceae", true, "Honingboom", "Vlinderbloemfamilie", false, true, false],
  ["Styphnolobium japonicum `Harry van Haaren`", "Styphnolobium", "Fabaceae", true, "Honingboom", "Vlinderbloemfamilie", false, true, false],
  ["Styphnolobium japonicum `Pendula`", "Styphnolobium", "Fabaceae", true, "Honingboom", "Vlinderbloemfamilie", false, true, false],
  ["Styphnolobium japonicum `Regent`", "Styphnolobium", "Fabaceae", true, "Honingboom", "Vlinderbloemfamilie", false, true, false],
  ["Styrax confusus", "Styrax", "Styracaceae", true, "Storaxboom", "Styracaceae", false, true, false],
  ["Styrax japonicus", "Styrax", "Styracaceae", true, "Japanse storaxboom", "Styracaceae", false, true, false],
  ["Styrax japonicus `Pink Chimes`", "Styrax", "Styracaceae", true, "Japanse storaxboom", "Styracaceae", false, true, false],
  ["Styrax japonicus `Snowfall`", "Styrax", "Styracaceae", true, "Japanse storaxboom", "Styracaceae", false, true, false],
  ["Styrax japonicus `Sohuksan`", "Styrax", "Styracaceae", true, "Japanse storaxboom", "Styracaceae", false, true, false],
  ["Styrax obassia", "Styrax", "Styracaceae", true, "Storaxboom", "Styracaceae", false, true, false],
  ["×Sycoparrotia semidecidua", "Sycoparrotia", "Hamamelidaceae", true, "Sycoparrotia", "Toverhazelaarfamilie", false, true, true],
  ["Symplocos paniculata", "Symplocos", "Symplocaceae", true, "Symplocos", "Symplocaceae", false, true, false],
  ["Tamarix ramosissima `Pink Cascade`", "Tamarix", "Tamaricaceae", true, "Tamariks", "Tamariskfamilie", true, true, false],
  ["Tetracentron sinense", "Tetracentron", "Trochodendraceae", true, "Tetracentron", "Trochodendraceae", false, true, false],
  ["Toona sinensis", "Toona", "Meliaceae", true, "Toona", "Meliaceae", false, true, false],
  ["Toona sinensis `Flamingo`", "Toona", "Meliaceae", true, "Toona", "Meliaceae", false, true, false],
  ["Torreya nucifera", "Torreya", "Taxaceae", false, "Noottaxus", "Taxusfamilie", false, true, false],
  ["Trachycarpus fortunei", "Trachycarpus", "Arecaceae", false, "Chinese Waaierpalm", "Palmenfamilie", false, true, false],
  ["Weigela `Nana Variegata`", "Weigela", "Caprifoliaceae", true, "Weigela", "Kamperfoeliefamilie", false, false, false],
  ["Zanthoxylum piperitum", "Zanthoxylum", "Rutaceae", true, "Japanse peperboom", "Wijnruitfamilie", false, false, false],
  ["Zanthoxylum simulans", "Zanthoxylum", "Rutaceae", true, "Sichuanpeper", "Wijnruitfamilie", false, true, false],
  ["Ziziphus jujuba", "Ziziphus", "Rhamnaceae", true, "Jujube", "Wegedoornfamilie", false, true, false],
  ["Prunus domestica `Excalibur`", "Prunus", "Rosaceae", true, "Pruim", "Rozenfamilie", true, true, false],
  ["Buddleja davidii `Empire Blue`", "Buddleja", "Scrophulariaceae", false, "Buddleja", "helmkruidfamilie", false, false, false],
  ["Sycopsis sinensis", "Sycopsis", "Hamamelidaceae", true, "Chinese vijghazelaar", "Toverhazelaarfamilie", false, false, false],
  ["Calycanthus occidentalis", "Calycanthus ", "Calycanthaceae", true, "Westerse specerijstruik", "Calycanthaceae", false, false, false],
  ["Camptotheca acuminata", "Camptotheca", "Nyssaceae", true, "Camptotheca acuminata", "Nyssaceae", false, true, false],
  ["Cedrela sinensis", "Cedrela", "Meliaceae", true, "Chinese mahonie", "Meliaceae", false, true, false],
  ["Cersis siliquastrum 'Alba'", "Cersis", "Fabaceae", true, "judasboom", "Vlinderbloemenfamilie", true, true, false],
  ["Ehretia dicksonii", "Ehretia", "Boraginaceae", true, "Ehretia dicksonii", "ruwbladigenfamilie ", false, true, false],
  ["Eucalyptus gunnii", "Eucalyptus", "Myrtaceae", false, "Cidergomboom", "Mirtefamilie", false, true, false],
  ["Euodia hupehensis", "Euodia", "Rutaceae", true, "Bijenboom", "Wijnruitfamilie", false, true, false],
  ["Hovenia dulcis", "Hovenia", "Rhamnaceae", true, "Japanse krentenboom", "Wegedoornfamilie", false, true, false],
  ["Maclura pomifera", "Maclura ", "Moraceae", true, "Osagedoorn", "Moerbeifamilie", false, true, false],
  ["+ Laburnocytisus adamii", "+ Laburnocytisus", "Fabaceae", true, "+ Laburnocytisus adamii", "Vlinderbloemenfamilie", false, true, false],
  ["Ginko biloba 'Tremonia'", "Ginko", "Ginkgoaceae", true, "Japanse notenboom", "Ginkgoaceae", false, true, false],
  ["Metrosideros excelsa", "Metrosideros", "Myrtaceae", false, "IJzerhoutboom", "Mirtefamilie", false, true, false],
  ["+ Crataegomespilus dardarii", "+ Crataegomespilus", "Rosaceae", false, "meidoorn", "Rozenfamilie", true, false, false],
  ["Pyrus communis 'Saint Remy'", "Pyrus", "Rosaceae", true, "stoofpeer 'Saint Remy'", "Rozenfamilie", true, true, false],
  ["Eriolobus Trilobatus", "Eriolobus", "Rosaceae", true, "Eriolobus Trilobatus", "Rozenfamilie", false, true, false],
  ["Symphytum grandiflorum 'Whisley Bleu'", "Symphytum", "Boraginaceae", false, "Smeerwortel", "ruwbladigenfamilie ", false, false, false],
  ["Chamaerops humilis", "Chamaerops", "Arecaceae", false, "Europese dwergpalm", "Palmenfamilie", true, true, false],
  ["Liquidambar orientalis", "Liquidambar", "Altingiaceae", true, "Oosterse amberboom", "Altingiaceae", false, true, false],
  ["Ailanthus vilmoriniana", "Ailanthus", "Simaroubaceae", true, "Hemelboom", "Hemelboomfamilie", false, true, false],
  ["Hippophae salicifolia 'Robert'", "Hippophae", "Elaeagnaceae", true, "Boomduindoorn", "Duindoornfamilie", false, true, false],
  ["Xanthocyparis nootkatensis", "Cupressus", "Cupressaceae", false, "Nootkacipres", "cipresfamilie ", false, true, false],
  ["Xanthocyparis nootkatensis 'Pendula'", "Cupressus", "Cupressaceae", false, "Treur nootkacipres", "cipresfamilie ", false, true, false],
  ["Firmiana simplex", "Firmiana", "Malvaceae", true, "Chinese parasolboom", "Kaasjeskruidfamilie", false, true, false],
  ["Decaisnea fargesii", "Decaisnea", "Lardizabalaceae", true, "Augurkenstruik", "Lardizabalaceae", false, false, false],
  ["Acer platanoides 'Globosum'", "Acer", "Sapindaceae", true, "Bolesdoorn of kogelesdoorn", "Zeepboomfamilie", true, true, false],
  ["Alnus incana 'Aurea'", "Alnus", "Betulaceae", true, "Goudels", "Berkenfamilie", true, true, false],
  ["Betula pendula 'Tristis'", "Betula", "Betulaceae", true, "treurberk", "Berkenfamilie", true, true, false],
  ["Catalpa bignonioides 'Nana'", "Catalpa ", "Bignoniaceae", true, "boltrompetboom of kogelvormige trompetboom", "Trompetboomfamilie", true, true, false],
  ["Fagus sylvatica 'Asplenifolia'", "Fagus", "Fagaceae", true, "Varenbeuk", "Napjesdragersfamilie", true, true, false],
  ["Fagus sylvatica 'Atropunicea'", "Fagus", "Fagaceae", true, "Bruine beuk", "Napjesdragersfamilie", true, true, false],
  ["Fagus sylvatica 'Pendula'", "Fagus", "Fagaceae", true, "Treurbeuk", "Napjesdragersfamilie", true, true, false],
  ["Fagus sylvatica 'Dawyck Purple'", "Fagus", "Fagaceae", true, "Rode zuilbeuk", "Napjesdragersfamilie", true, true, false],
  ["Fraxinus excelsior 'Diversifolia'", "Fraxinus", "Oleaceae", true, "Éenbladige es", "Olijffamilie", true, true, false],
  ["Fraxinus excelsior 'Jaspidea'", "Fraxinus", "Oleaceae", true, "Goudes", "Olijffamilie", true, true, false],
  ["Gleditsia triacanthos f. inermis", "Gleditsia", "Fabaceae", true, "Doornloze valse christusdoorn", "Vlinderbloemenfamilie", true, true, false],
  ["Laburnum ×watereri 'Vossi'", "Laburnum", "Fabaceae", true, "Gouden regen", "Vlinderbloemenfamilie", true, true, true],
  ["Populus alba 'Pyramidalis'", "Populus", "Salicaceae", true, "Zuilabeel", "Wilgenfamilie", false, true, false],
  ["Populus ×canescens 'De Moffart'", "Populus", "Salicaceae", true, "Grauwe abeel", "Wilgenfamilie", true, true, true],
  ["Populus ×canadensis 'Robusta'", "Populus", "Salicaceae", true, "Canadese populier", "Wilgenfamilie", false, true, true],
  ["Populus nigra 'Italica'", "Populus", "Salicaceae", true, "Italiaanse populier", "Wilgenfamilie", true, true, false],
  ["Prunus × gondouinii 'Schnee'", "Prunus", "Rosaceae", true, "Sierkers 'Schnee'", "Rozenfamilie", true, true, true],
  ["Robinia pseudoacacia 'Frisia'", "Robinia", "Fabaceae", true, "Gele acacia", "Vlinderbloemenfamilie", true, true, false],
  ["Robinia pseudoacacia 'Umbraculifera'", "Robinia", "Fabaceae", true, "Bolacacia", "Vlinderbloemenfamilie", true, true, false],
  ["Salix alba 'Tristis'", "Salix", "Salicaceae", true, "Gele treurwilg of treurwilg", "Wilgenfamilie", true, true, false],
  ["Salix matsudana 'Tortuosa'", "Salix", "Salicaceae", true, "Kronkelwilg, krulwilg of chinese wilg", "Wilgenfamilie", false, true, false],
  ["Tilia ×europaea 'Pallida'", "Tilia", "Malvaceae", true, "Koningslinde of Leilinde", "Kaasjeskruidfamilie", true, true, true],
  ["COLUTEA ARBORESCENS", "Colutea", "Fabaceae", true, "Colutea arborescens", "Vlinderbloemenfamilie", true, false, false],
  ["LIBOCEDRUS DECURRENS", "Calocedrus ", "Cupressaceae", false, "Wierookceder", "Cipresfamilie", false, true, false],
  ["NEILLIA", "Neillia", "Rosaceae", false, "Neillia", "Rozenfamilie", false, false, false],
  ["RUMEX", "Rumex", "Polygonaceae", false, "Zuring", "Duizendknoopfamilie", true, false, false],
  ["RUSCUS ACULEATUS", "Ruscus", "Asparagaceae", false, "Muizendoorn", "Aspergefamilie", true, false, false],
  ["Salvia nemorosa 'OSTFRIESLAND'", "Salvia", "Lamiaceae", false, "Salie", "lipbloemenfamilie ", true, false, false],
  ["amelachier leavis", "Amelanchier", "Rosaceae", true, "Drents krentenboompje", "Rozenfamilie", true, true, false],
  ["amelanchie arborea 'robin hill'", "Amelanchier", "Rosaceae", true, "Krentenboompje", "Rozenfamilie", false, true, false],
  ["cederus atlantica 'glauca'", "Cedrus", "Pinaceae", false, "Blauwe atlasceder", "Dennenfamilie", false, true, false],
  ["gledistia", "Gleditsia", "Fabaceae", false, "Valse christusdoorn", "Vlinderbloemenfamilie", false, true, false],
  ["gledistia triacanthos 'imperial'", "Gleditsia", "Fabaceae", false, "Valse christusdoorn", "Vlinderbloemenfamilie", false, true, false],
  ["Salix ×sepulcralis 'Chrysocoma'", "Salix", "Salicaceae", true, "Treurwilg", "Wilgenfamilie", false, true, true]
]

let filteredTrees = species;

function filtertrees(target) {
  const search = target.value.toLowerCase();
  const decidious = document.getElementById("decidious").checked;
  const evergreen = document.getElementById("evergreen").checked;
  const tree = document.getElementById("tree").checked;
  const nontree = document.getElementById("nontree").checked;
  filteredTrees = species.filter((species) => {
    return (species[0].toLowerCase().includes(search) ||
        species[1].toLowerCase().includes(search) ||
        species[2].toLowerCase().includes(search) ||
        species[4].toLowerCase().includes(search) ||
        species[5].toLowerCase().includes(search)
      ) &&
      (decidious && species[3] || evergreen && !species[3]) &&
      (tree && species[7] || nontree && !species[7])
  });
  const table = document.getElementById("species");
  const oldTable = document.querySelector('.table-container');
  if (oldTable) {
    oldTable.removeEventListener('click', handleTableClick);
  }
  table.innerHTML = `
    <div class="table-container">
      <table>
        <thead>
        <tr>
          <th><span>Soort</span></th>
          <th><span>Geslacht</span></th>
          <th><span>Familie</span></th>
          <th><span>Naam</span></th>
          <th><span>Familienaam</span></th>
          <th><span>boom</span></th>
          <th><span>bladverliezend</span></th>
        </tr>
        </thead>
        <tbody>
          ${filteredTrees.map((species) => {
            return `
            <tr>
                <td>${species[0]}</td>
                <td>${species[1]}</td>
                <td>${species[2]}</td>
                <td>${species[4]}</td>
                <td>${species[5]}</td>
                <td>${species[7]?'x':'-'}</td>
                <td>${species[3]?'x':'-'}</td>
            </tr>
            `
        }).join('')}
        </tbody>
      </table>
    </div>
    `;
  let tableElement = document.querySelector('table');
  tableElement.addEventListener('click', handleTableClick);
}

function handleTableClick(e) {
  const columnmap = ['soort', 'geslacht', 'familie', 'naam', 'familienaam', 'boom', 'bladverliezend'];
  const columnindex = [0, 1, 2, 4, 5, 7, 3]
  if (e.target.tagName === 'TD' || e.target.tagName === 'TH') {
    let rowIndex = e.target.parentElement.rowIndex;
    let cellIndex = e.target.cellIndex;

    // rowIndex and cellIndex are both 0-based.
    console.log('Row: ' + rowIndex + ', Cell: ' + cellIndex);
    const value = filteredTrees[rowIndex - 1][columnindex[cellIndex]];
    const attrname = columnmap[cellIndex];
    document.querySelector('#selected').innerHTML = `
      <b>${attrname}</b>: ${value}
    `;
  }
}

function treechange(target) {
  if (!target.checked) {
    if (target.id === "tree") {
      document.getElementById("nontree").checked = true;
    } else {
      document.getElementById("tree").checked = true;
    }
  }
  filtertrees(document.getElementById("filter"));
}

function decidiouschange(target) {
  if (!target.checked) {
    if (target.id === "decidious") {
      document.getElementById("evergreen").checked = true;
    } else {
      document.getElementById("decidious").checked = true;
    }
  }
  filtertrees(document.getElementById("filter"));
}

function init() {
  filtertrees(document.getElementById("filter"));
}